name: Django WebApp CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip project folder
      run: |
        zip -r django-webapp.zip . -x "*.git*" "*.venv*" "__pycache__*" "*.pytest_cache*" "*.mypy_cache*"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: django-webapp
        path: django-webapp.zip
